run:
  tests: false

linters-settings:
  govet:
    check-shadowing: false
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - maligned
    - lll
    - gocritic
    - gochecknoinits
    - gochecknoglobals
    - wsl
    - unparam

issues:
  exclude-use-default: false